export HOMEBREW_NO_AUTO_UPDATE=1
export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  zsh-completions
  zsh-autosuggestions
  fast-syntax-highlighting
)




# end -> startship theme
eval "$(starship init zsh)"
source $ZSH/oh-my-zsh.sh

